callbacks:
  - _target_ : pytorch_lightning.callbacks.ModelCheckpoint
    monitor : "val_dice"
    mode : "max"
    save_top_k : 1
    save_last : true
    filename : "best_model"
    verbose : true


  - _target_ : pytorch_lightning.callbacks.EarlyStopping
    monitor: "val_dice"
    patience: 10
    mode: "max"
    min_delta: 0.001
    verbose: true