# config/config.yaml
defaults:
  - data: data
  - training: training
  - model: unet
  - callbacks: callbacks
  - transforms: transforms 
  - _self_

# Global settings
debug: false

wandb_logging :
  enabled : true

# Weights & Biases
wandb:
  project: "PolypHydraMonai"
  entity: null
  tags: []
  name : "segmentation_run"

# Paths
paths:
  output_dir: ${hydra:runtime.output_dir}
  checkpoint_dir: "checkpoints"
  log_dir: ${paths.output_dir}/logs


# hydra:
#   job:
#     chdir: false